// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeminjamanRuangApi.Data;

#nullable disable

namespace PeminjamanRuangApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260216170846_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PeminjamanRuangApi.Models.Peminjaman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NamaPeminjam")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NamaRuangan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Peminjamans");
                });

            modelBuilder.Entity("PeminjamanRuangApi.Models.Ruang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Kapasitas")
                        .HasColumnType("int");

                    b.Property<string>("Lokasi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NamaRuangan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Ruangs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Kapasitas = 30,
                            Lokasi = "Gedung D3",
                            NamaRuangan = "Lab RPL"
                        },
                        new
                        {
                            Id = 2,
                            Kapasitas = 30,
                            Lokasi = "Gedung D4",
                            NamaRuangan = "Lab Database"
                        },
                        new
                        {
                            Id = 3,
                            Kapasitas = 100,
                            Lokasi = "Gedung D3",
                            NamaRuangan = "Teater PENS"
                        },
                        new
                        {
                            Id = 4,
                            Kapasitas = 30,
                            Lokasi = "Gedung D4",
                            NamaRuangan = "Lab APD"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
